# railway.toml - Railway deployment configuration
[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend/"
dockerfile = "backend/Dockerfile"

[[services]]
name = "frontend"
source = "frontend/"